In [17]:
import numpy as np

In [18]:
a = np.array([1, 2, 3])

In [19]:
b = np.array([4, 5, 6])

In [20]:
print(a + b)

[5 7 9]


In [21]:
print(a - b)

[-3 -3 -3]


In [22]:
print(a * b)

[ 4 10 18]


In [23]:
print(a / b)

[0.25 0.4  0.5 ]


In [24]:
print(np.subtract(a, b))

[-3 -3 -3]


In [25]:
print(np.multiply(a, b))

[ 4 10 18]


In [26]:
print(np.divide(a, b))

[0.25 0.4  0.5 ]


In [27]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 2, 3])

In [28]:
print(a+b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [29]:
c = np.array([[1], [2], [3]])
d = np.array([1, 2, 3])

In [30]:
print(c+d)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [31]:
c = np.array([[1,2], [3,4]])
d = np.array([[5,6], [7,8]])

In [32]:
print(c@d)

[[19 22]
 [43 50]]


In [33]:
e = np.array([[1,2],[3,4]])

In [35]:
print(np.linalg.inv(e))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [37]:
print(np.linalg.det(e))

-2.0000000000000004
