In [29]:
import numpy as np

In [30]:
data = np.array([[1,2,3],[4,5,6]])

In [31]:
total = np.sum(data, axis = None)
print(total)

21


In [32]:
total_column = np.sum(data, axis = 0)
print(total_column)

[5 7 9]


In [33]:
data = np.array([1,2,3,4,5,6])

In [34]:
minimum = np.min(data)
maximum = np.max(data)
print(minimum)
print(maximum)

1
6


In [35]:
data = np.array([[1,2,3],[4,5,6]])
minimum = np.min(data)
maximum = np.max(data)
average = np.mean(data)
middle = np.median(data)
std_dev = np.std(data)
variance = np.var(data)
print(minimum)
print(maximum)
print(average)
print(middle)
print(std_dev)
print(variance)

1
6
3.5
3.5
1.707825127659933
2.9166666666666665


In [36]:
data = np.array([5,3,1,2,4,])
sorted_data = np.sort(data)

print(data)
print(sorted_data)

[5 3 1 2 4]
[1 2 3 4 5]


In [39]:
data = np.array([5,3,1,2,4])
partitioned_data = np.partition(data, 3)

print(data)
print(partitioned_data)

data = np.array([6,4,2,3,5])
partitioned_data = np.partition(data, 3)

print(data)
print(partitioned_data)

[5 3 1 2 4]
[2 1 3 4 5]
[6 4 2 3 5]
[3 2 4 5 6]


In [41]:
data = np.array([9,5,3,1,2,4,6,8,7])
partitioned_data = np.partition(data, 6)

print(partitioned_data)

[6 2 3 1 5 4 7 8 9]


In [44]:
data = np.array([9,5,3,1,2,4,6,8,7])
index = np.where( data > 3)

for idx in index:
    print(data[idx])

[9 5 4 6 8 7]


In [47]:
arr1 = np.array([True,False,True])
arr2 = np.array([False,False,True])

print("Logical AND:", np.logical_and(arr1,arr2))
print("Logical OR:", np.logical_or(arr1,arr2))
print("Logical NOT:", np.logical_not(arr1,arr2))

Logical AND: [False False  True]
Logical OR: [ True False  True]
Logical NOT: [False  True False]
