In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
print("Original array: ",arr)
print("First element: ",arr[0])
print("Last array: ",arr[-1])

Original array:  [1 2 3 4 5]
First element:  1
Last array:  5


In [4]:
arr[0] = 10
print("Array after modification: ", arr)

Array after modification:  [10  2  3  4  5]


In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
print("Original array: \n",arr)
print("Element at position (1,1): ",arr[1,1])

Original array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at position (1,1):  5


In [7]:
arr[0, 0] = 10
print("Array after modification: \n", arr)

Array after modification: 
 [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [8]:
arr = np.array([1,2,3,4,5])

In [10]:
print("Original array: \n",arr)
print("Element greater than 2: ",arr[arr > 2])

Original array: 
 [1 2 3 4 5]
Element greater than 2:  [3 4 5]


In [12]:
slice_arr = arr[1:4]
print("Slice of the array: ", slice_arr)

Slice of the array:  [2 3 4]
Original array after modification:  [1 2 3 4 5]


In [14]:
slice_arr[0] = 10

In [15]:
print("Slice after modification: ", slice_arr)
print("Original array after modification: ", arr)

Slice after modification:  [10  3  4]
Original array after modification:  [ 1 10  3  4  5]


In [ ]:
print('test')