In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
np.save('array', arr)

In [6]:
loaded_arr = np.load('array.npy')
print(loaded_arr)

[1 2 3 4 5]


In [7]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.savetxt('array.txt', arr_2d)
load_arr_2d = np.loadtxt('array.txt')
print(load_arr_2d)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [10]:
data = np.genfromtxt('train.csv', delimiter=',')
print(data)

[[        nan         nan         nan ...         nan         nan
          nan]
 [1.00000e+00 6.00000e+01         nan ...         nan         nan
  2.08500e+05]
 [2.00000e+00 2.00000e+01         nan ...         nan         nan
  1.81500e+05]
 ...
 [1.45800e+03 7.00000e+01         nan ...         nan         nan
  2.66500e+05]
 [1.45900e+03 2.00000e+01         nan ...         nan         nan
  1.42125e+05]
 [1.46000e+03 2.00000e+01         nan ...         nan         nan
  1.47500e+05]]
